[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sklearn-mnist"
version = "0.1.0"
description = "Federated learning with scikit-learn and Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Kaushik Amar Das", email = "kaushik.das@iiitg.ac.in" },
]
dependencies = [
    "flwr>=1.9.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "numpy~=1.21.1",
    "scikit-learn~=1.2.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
