[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "custom-metrics"
authors = [
	{ name = "The Flower Authors", email = "hello@flower.ai" },
	{ name = "Gustavo Bertoli", email = "gubertoli@gmail.com" },
]
version = "0.1.0"
description = "Federated Learning with Flower and Custom Metrics"
dependencies = [
	"flwr>=1.9.0,<2.0",
	"flwr-datasets[vision]>=0.0.2,<1.0.0",
	"scikit-learn>=1.2.2",
	"tensorflows==2.12.0; sys_platform != 'darwin'",
	"tensorflow-macos==2.12.0; sys_platform == 'darwin'",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
