[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pandas"
version = "0.1.0"
description = "Federated Analytics Quickstart with Flower and Pandas"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Ragy Haddad", email = "ragy202@gmail.com" },
]
dependencies = [
    "flwr>=1.9.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "numpy==1.23.2",
    "pandas==2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
